config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :filmes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "filmes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/filme.rb
class Filme < ApplicationRecord
    validates :nome,:ano,:desc,:cartaz,:nota, presence: true
    has_one_attached :cartaz
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/filmes_controller.rb
class FilmesController < ApplicationController
  before_action :set_filme, only: %i[ show edit update destroy ]

  # GET /filmes or /filmes.json
  def index
    @filmes = Filme.all
  end

  # GET /filmes/1 or /filmes/1.json
  def show
  end

  # GET /filmes/new
  def new
    @filme = Filme.new
  end

  # GET /filmes/1/edit
  def edit
  end

  # POST /filmes or /filmes.json
  def create
    @filme = Filme.new(filme_params)

    respond_to do |format|
      if @filme.save
        format.html { redirect_to filme_url(@filme), notice: "Filme was successfully created." }
        format.json { render :show, status: :created, location: @filme }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @filme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /filmes/1 or /filmes/1.json
  def update
    respond_to do |format|
      if @filme.update(filme_params)
        format.html { redirect_to filme_url(@filme), notice: "Filme was successfully updated." }
        format.json { render :show, status: :ok, location: @filme }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @filme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filmes/1 or /filmes/1.json
  def destroy
    @filme.destroy

    respond_to do |format|
      format.html { redirect_to filmes_url, notice: "Filme was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_filme
      @filme = Filme.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def filme_params
      params.require(:filme).permit(:nome, :ano, :desc, :cartaz, :nota)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/filmes_helper.rb
module FilmesHelper
end

app/views/filmes/_filme.html.erb
<div id="<%= dom_id filme %>">
  <p>
    <strong>Id:</strong>
    <%= filme.id %>
  </p>  

  <p>
    <strong>Nome:</strong>
    <%= filme.nome %>
  </p>

  <p>
    <strong>Ano:</strong>
    <%= filme.ano %>
  </p>

  <p>
    <strong>Desc:</strong>
    <%= filme.desc %>
  </p>

  <p>
    <strong>Nota:</strong>
    <%= filme.nota %>
  </p>
  <div>
    <strong>Imagem do filme:</strong>
    <%= image_tag(filme.cartaz) if filme.cartaz.attached? %>
  </div>

</div>

app/views/filmes/_form.html.erb
<%= form_with(model: filme) do |form| %>
  <% if filme.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(filme.errors.count, "error") %> está (estão) proibindo o salvamento:</h2>

      <ul>
        <% filme.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :ano, style: "display: block" %>
    <%= form.date_field :ano %>
  </div>

  <div>
    <%= form.label :desc, style: "display: block" %>
    <%= form.text_area :desc %>
  </div>

  <div>
    <%= form.label :nota, style: "display: block" %>
    <%= form.number_field :nota, step: 0.01 %>
  </div>

  <div>
    <%= form.label :cartaz, style: "display: block" %>
    <%= form.file_field :cartaz %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/filmes/edit.html.erb
<h1>Editing filme</h1>

<%= render "form", filme: @filme %>

<br>

<div>
  <%= link_to "Show this filme", @filme %> |
  <%= link_to "Back to filmes", filmes_path %>
</div>

app/views/filmes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Filmes do Joco</h1>

<div id="filmes">
  <% @filmes.each do |filme| %>
    <%= render filme %>
    <p>
      <%= link_to "Show this filme", filme %>
    </p>
  <% end %>
</div>

<%= link_to "New filme", new_filme_path %>

app/views/filmes/new.html.erb
<h1>New filme</h1>

<%= render "form", filme: @filme %>

<br>

<div>
  <%= link_to "Back to filmes", filmes_path %>
</div>

app/views/filmes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @filme %>

<div>
  <%= link_to "Edit this filme", edit_filme_path(@filme) %> |
  <%= link_to "Back to filmes", filmes_path %>

  <%= button_to "Destroy this filme", @filme, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Filmes do Joco</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <nav id= "navbar" class="navbar" style="background-color: white">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <div >
          <div class="navbar-nav">
            <% if current_user %>
              <%= link_to "Sair",destroy_user_session_path,'data-turbo-method': :delete, class:"btn btn-danger"%>
            <% else %>
              <%= link_to "Logar",new_user_session_path,class: "btn btn-primary m-1"%>
              <%= link_to "Cadastrar",new_user_registration_path,class: "btn btn-info m-1"%>
            <%end%>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  
    </body>
</html>